Documentation:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - config/**/*
    - db/**/*
    - lib/tasks/seed.rake
    - script/rails
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - db/**/*
    - config/**/*
Metrics/AbcSize:
  Exclude:
    - db/**/*
Rails/FilePath:
  Exclude:
    - 'lib/tasks/seed.rake'
